Contact form
johnalpha74/my-portfolio pull request #4
Opened 2022-04-26 11:55 UTC by johnalpha74

Add contact form

2022-04-26 14:33 UTC, AnselemOdims requested changes
### Hi @johnalpha74 , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-26 14:33 UTC, AnselemOdims commented on index.html
> +                    <form class="form-block" action="submit">
- [ ] Please make sure the `form` as an action and a method attribute that integrates with the formspree service.

2022-04-26 14:33 UTC, AnselemOdims commented on index.html
> +                            <input placeholder="Last Name" type="text">
- [ ] Please kindly include a `maxlength` attribute to the firstname and lastname inputs and give it a value of 30
- [ ] Please include the required attribute for the name input fields

2022-04-26 14:33 UTC, AnselemOdims commented on index.html
> +                        <textarea placeholder="Message" name="textarea" id="textarea" cols="30" rows="6"></textarea>
- [ ] Please include the required attribute for the email and textarea input fields

2022-04-26 14:33 UTC, AnselemOdims commented on index.html
> +        </div>
- [ ] Please ensure that you stick to the design guideline as much as possible
- [ ] The design only has one input field for `fullname`. Please only use one name input
- [ ] Please ensure that the heading text is aligned to the center like that of the original design
- [ ] Please kindly include the icons and email that is below the form in the original design

### Your Design
![image](https://user-images.githubusercontent.com/43995830/165323579-ae572a01-9d0c-4d12-8f3d-8a9074b07678.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/165323860-277569c6-9fde-4576-a8bc-d7629ddadf4d.png)

2022-04-26 16:28 UTC, chrystalme requested changes
# Hello @johnalpha74, 
![Almost there](https://media.giphy.com/media/dEPGknRiEniec/giphy.gif)

Great work on making the changes 👏 👍🏽 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes ♻️ 

- [ ] Your README.md file has a bug. Kindly fix it.

- [ ] _Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Also, you can reach me on [Twitter](https://twitter.com/afam_ifeanyi) or [Slack](https://microverse-community.slack.com/team/U019ZC99KFA)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 16:28 UTC, chrystalme commented on index.html
> +                            <!-- <input placeholder="Last Name" type="text" maxlength="30" required> -->
Kindly remove commented code from your code-base. To keep your code-base clean and looking professional.

2022-04-26 16:28 UTC, chrystalme commented on index.html
> +                            <!-- <input placeholder="Last Name" type="text" maxlength="30" required> -->
Kindly remove commented code from your code-base. To keep your code-base clean and looking professional.

2022-04-26 16:28 UTC, chrystalme commented on index.html
> +                    <form class="form-block" action="https://formspree.io/f/xeqnpgqv" method="post">
Why not use `<section>` tag for the contact form section. This make your code SEO friendly and semantically correct.

2022-04-27 10:38 UTC, prolajumokeoni approved these changes
Hi Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯 
- Good Pr and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Kindly ensure that as partners you always have balanced commits in pair programming project 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 11:50 UTC, merged